PlatinumReport/PlatinumReport/Controllers/ReportController.cs
using Newtonsoft.Json;
using PlatinumDataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlatinumReport.Controllers
{
    public class ReportController : Controller
    {

        /// <summary>
        /// Display the Control to get the device profile based on service tag and date.
        /// </summary>
        /// <param name="reportName">Name of the Report</param>
        /// <returns>returns view on the page.</returns>
        [HttpGet]
        public ActionResult GetDeviceProfile(string reportName)
        {
            ViewBag.ReportName = reportName;
            return View();
        }

        /// <summary>
        /// get the list of all device profile based on service tag and date.
        /// </summary>
        /// <param name="model">Model obj contains service tag and date provided by end-user to get the device profile</param>
        /// <returns>List of Device Profile data.</returns>
        public JsonResult GetDeviceProfileData(string model)
        {
            if (ModelState.IsValid)
            {
                PlatinumReports.Models.SearchDeviceProfile deviceObj = JsonConvert.DeserializeObject<PlatinumReports.Models.SearchDeviceProfile>(model);
                DeviceEntity deviceProfile = null;
                try
                {
                    PlatinumMapper<PlatinumReports.Models.SearchDeviceProfile, SearchDeviceProfile> mapObj = new PlatinumMapper<PlatinumReports.Models.SearchDeviceProfile, SearchDeviceProfile>();
                    PlatinumMapper<DeviceEntity, PlatinumReports.Models.DeviceEntity> mapDeviceObj = new PlatinumMapper<DeviceEntity, PlatinumReports.Models.DeviceEntity>();
                    var dal = new PlatinumRepository();
                    SearchDeviceProfile newSearchDeviceProfile = mapObj.Translate(deviceObj);
                    deviceProfile = dal.GetDeviceProfile(newSearchDeviceProfile);
                    var modelsDeviceProfile = mapDeviceObj.Translate(deviceProfile);
                    if (modelsDeviceProfile != null)
                    {
                        return Json(modelsDeviceProfile, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(null, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }


        /// <summary>
        /// Display the Control to get the device history based on service tag, from date and to date.
        /// </summary>
        /// <param name="reportName">Name of the Report</param>
        /// <returns>returns view on the page.</returns>
        public ActionResult GetDeviceHistory(string reportName)
        {
            ViewBag.ReportName = reportName;
            return View();
        }

        /// <summary>
        /// get the list of all device history based on service tag and date.
        /// </summary>
        /// <param name="model">Model obj contains service tag,from date and to date provided by end-user to get the device history</param>
        /// <returns>List of Device history data.</returns>
        public JsonResult GetDeviceHistoryData(string model)
        {
            if (ModelState.IsValid)
            {
                PlatinumReports.Models.SearchDeviceHistory deviceObj = JsonConvert.DeserializeObject<PlatinumReports.Models.SearchDeviceHistory>(model);
                IEnumerable<DeviceEntity> deviceList = null;
                try
                {
                    PlatinumMapper<PlatinumReports.Models.SearchDeviceHistory, SearchDeviceHistory> mapObj = new PlatinumMapper<PlatinumReports.Models.SearchDeviceHistory, SearchDeviceHistory>();
                    PlatinumMapper<DeviceEntity, PlatinumReports.Models.DeviceEntity> mapList = new PlatinumMapper<DeviceEntity, PlatinumReports.Models.DeviceEntity>();
                    var dal = new PlatinumRepository();
                    var newSearchDeviceHistory = mapObj.Translate(deviceObj);
                    deviceList = dal.GetDeviceHistory(newSearchDeviceHistory);
                    var modelsDeviceList = mapList.TranslateList(deviceList);
                    if (modelsDeviceList != null)
                    {
                         return Json(modelsDeviceList, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(modelsDeviceList, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception ex)
                {
                    return Json(ex.InnerException);
                }
            }
            else
            {
                return Json(null);
            }
        }
        /// <summary>
        /// Display the Control to get the Event history based on service tag, from date and to date.
        /// </summary>
        /// <param name="reportName">Name of the Report</param>
        /// <returns>returns view on the page.</returns>
        [HttpGet]
        public ActionResult GetEventHistory(string reportName)
        {
            ViewBag.ReportName = reportName;
            return View();
        }

        /// <summary>
        /// get the list of all Event history based on service tag and date.
        /// </summary>
        /// <param name="model">Model obj contains service tag,from date and to date provided by end-user to get the Event history</param>
        /// <returns>List of Device history data.</returns>
        public ActionResult GetEventHistoryData(string model)
        {
            if (ModelState.IsValid)
            {
                PlatinumReports.Models.SearchEventHistory eventObj = JsonConvert.DeserializeObject<PlatinumReports.Models.SearchEventHistory>(model);
                IEnumerable<EventEntity> eventList = null;
                try
                {
                    PlatinumMapper<PlatinumReports.Models.SearchEventHistory, SearchEventHistory> mapObj = new PlatinumMapper<PlatinumReports.Models.SearchEventHistory, SearchEventHistory>();
                    PlatinumMapper<EventEntity, PlatinumReports.Models.EventEntity> mapList = new PlatinumMapper<EventEntity, PlatinumReports.Models.EventEntity>();
                    var dal = new PlatinumRepository();
                    var newSearchEventHistory = mapObj.Translate(eventObj);
                    eventList = dal.GetEventHistory(newSearchEventHistory);

                    var modelsEventList = mapList.TranslateList(eventList);
                    if (modelsEventList != null)
                    {
                        return View(modelsEventList);
                    }
                    else
                    {
                        return View();
                    }
                }
                catch (Exception ex)
                {
                    return View(ex.InnerException);
                }
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Retrieve the details about the Reports
        /// </summary>
        /// <returns>List of Reports and its details</returns>
        public ActionResult GetReports()
        {
            PlatinumRepository dal = new PlatinumRepository();
            var data = dal.GetReportDetails();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

PlatinumReport/PlatinumReport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dell Platinum Services</title>
    <link rel="icon"
          type="image/png"
          href="~/dLogo.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/sidebar-menu.css" rel="stylesheet" />



    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = '17%';
            document.getElementById("main").style.marginLeft = '17%';
        }
        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $.ajax(
                {
                    type: "GET",
                    datatype: 'json',
                    contentType: 'applcation/json',
                    url: '@Url.Action("GetReports","Report")',
                    success: function (result1) {
                        var s = '';
                        debugger;
                        for (var i = 0; i < result1.length; i++) {
                            var urLink = '@Url.Action("vName","cName")';
                            urLink = urLink.replace('vName', result1[i].ViewName);
                            urLink = urLink.replace('cName', result1[i].ControllerName);
                            s = s + '<li>';
                            s = s + '<a href=' + urLink + '?reportName=' + encodeURI(result1[i].ReportHeader) + '>';
                            s = s + '<i class="fa fa-circle-o text-red">' + '</i> <span>' + result1[i].ReportHeader + '</span></a></li>';
                        }
                        $('#sideMenu').append(s);
                    }
                });
        });
    </script>
    <style>
        .w3-padding-1 {
            padding-top: 1px !important;
            padding-bottom: 1px !important;
        }

        .w3-center {
            text-align: center !important;
        }

        .w3-container:after, .w3-container:before {
            content: "";
            display: table;
            clear: both;
        }

        footer {
            background-color: #0C1F3C;
            color: #f5f5f5;
            padding-top: 0px;
            position: fixed;
            height: 25px;
            bottom: 0px;
            left: 0px;
            right: 0px;
            margin-bottom: 0px;
        }

            footer a {
                color: #f5f5f5;
            }

                footer a:hover {
                    color: #777;
                    text-decoration: none;
                }

        .demo {
            background: #77C9D4;
        }

        .serviceBox {
            border: 1px solid #0e6787;
            /*border-right: 4px solid #0e6787;*/
            background: #fff;
            margin-bottom: 20px;
            padding: 20px 10px 10px;
            transition: all 0.3s ease-in-out 0s;
        }

            .serviceBox:hover {
                border-right: 7px solid;
                border-color: #77C9D4;
                background-color: #0e6787;
            }

            .serviceBox .service-icon {
                display: block;
                width: 35px;
                height: 35px;
                line-height: 35px;
                border-radius: 50%;
                background: #27c9c6;
                text-align: center;
                float: left;
                font-size: 20px;
                color: #fff;
                margin: 0 20px 0 0;
                transition: all 0.3s ease-in-out 0s;
            }

            .serviceBox .title {
                display: inline-block;
                font-size: 20px;
                color: #041829;
                border-bottom: 3px solid #d9e7ed;
                padding-bottom: 6px;
                margin: 0 0 20px 0;
                transition: all 0.3s ease-in-out 0s;
            }

            .serviceBox:hover .title {
                border-color: #27c9c6;
                color: #fff;
            }

            .serviceBox .description {
                font-size: 16px;
                color: #929a9c;
                margin: 0 0 11px 0;
            }

            .serviceBox .read-more {
                display: inline-block;
                font-size: 16px;
                font-weight: 500;
                color: #27c9c6;
                text-transform: capitalize;
            }

                .serviceBox .read-more:hover {
                    letter-spacing: 0.3px;
                    color: #27c9c6;
                }

                .serviceBox .read-more:after {
                    content: "\f0da";
                    font-family: 'FontAwesome';
                    font-size: 16px;
                    color: #27c9c6;
                    margin-left: 7px;
                    transition: all 0.2s ease 0s;
                }

        .dHeader {
            background-color: #0B3C5D;
            color: #fff;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #0F1626;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 16px;
                color: white;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover, .offcanvas a:focus {
                    color: #f1f1f1;
                }

            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        .headerDell {
            background-color: #1D2731;
            color: white;
            text-transform: uppercase;
            margin-bottom: 30px;
        }

        .affix {
            top: 0;
            width: 100%;
        }

            .affix + .tab-content {
                padding-top: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding: 0px;
        }

        .open .dropdown-toggle {
            color: #fff;
            background-color: #555 !important;
        }

        .dropdown-menu li a {
            color: #000 !important;
        }

            .dropdown-menu li a:hover {
                background-color: red !important;
            }
    </style>
</head>

<body id="main">
    <!-- Header -->
    <div class="dHeader">
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <ul class="sidebar-menu" id="sideMenu">
                <li class="sidebar-header">HOME</li>
                <li>
                    <a href='@Url.Action("Index", "Home",new { id = "" })'>
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-header">REPORTS</li>
            </ul>
        </div>
        <span style="font-size:30px;cursor:pointer" onclick="openNav()" id="bar">&#9776;</span>
        <header class="w3-container w3-center w3-padding-1">
            <h1><b>DELL PLATINUM SERVICES</b></h1>
            <p>Welcome to the Services of <span class="w3-tag">DELL.</span></p>
        </header>
    </div>
    <div class="headerDell">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab tooltip" title="Home Page" href='@Url.Action("Index", "Home",new { id = "" })'>Home</a></li>
            <li><a data-toggle="tab tooltip" title="View Reports" href='@Url.Action("GetDeviceHistory", "Report", new { reportName = "Device History" })'>Reports</a></li>
        </ul>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="text-center">
        <p>DPS&reg;Dell Platinum Services Ver 2.1 &copy;@DateTime.Now.Year</p>
    </footer>    
    @RenderSection("scripts", required: false)
</body>
</html>

PlatinumReport/PlatinumReport/Views/Shared/_ReportLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dell Platinum Services</title>
    <link rel="icon"
          type="image/png"
          href="~/dLogo.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/sidebar-menu.css" rel="stylesheet" />
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = '17%';
            document.getElementById("main").style.marginLeft = '17%';
        }
        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $.ajax(
                {
                    type: "GET",
                    datatype: 'json',
                    contentType: 'applcation/json',
                    url: '@Url.Action("GetReports","Report")',
                    success: function (result1) {
                        var s = '';
                        debugger;
                        for (var i = 0; i < result1.length; i++) {
                            var urLink = '@Url.Action("vName","cName")';
                            urLink = urLink.replace('vName', result1[i].ViewName);
                            urLink = urLink.replace('cName', result1[i].ControllerName);
                            s = s + '<li>';
                            s = s + '<a href=' + urLink + '?reportName=' + encodeURI(result1[i].ReportHeader) + '>';
                            s = s + '<i class="fa fa-circle-o text-red">' + '</i> <span>' + result1[i].ReportHeader + '</span></a></li>';
                        }
                        $('#sideMenu').append(s);
                    }
                });
        });
    </script>
    <style>
        .w3-padding-1 {
            padding-top: 1px !important;
            padding-bottom: 1px !important;
        }

        .w3-center {
            text-align: center !important;
        }

        .w3-container:after, .w3-container:before {
            content: "";
            display: table;
            clear: both;
        }

        footer {
            background-color: #0C1F3C;
            color: #f5f5f5;
            padding-top: 0px;
            position: fixed;
            height: 25px;
            bottom: 0px;
            left: 0px;
            right: 0px;
            margin-bottom: 0px;
        }

            footer a {
                color: #f5f5f5;
            }

                footer a:hover {
                    color: #777;
                    text-decoration: none;
                }

        .demo {
            background: #77C9D4;
        }

        .serviceBox {
            border: 1px solid #0e6787;
            /*border-right: 4px solid #0e6787;*/
            background: #fff;
            margin-bottom: 20px;
            padding: 20px 10px 10px;
            transition: all 0.3s ease-in-out 0s;
        }

            .serviceBox:hover {
                border-right: 7px solid;
                border-color: #77C9D4;
                background-color: #0e6787;
            }

            .serviceBox .service-icon {
                display: block;
                width: 35px;
                height: 35px;
                line-height: 35px;
                border-radius: 50%;
                background: #27c9c6;
                text-align: center;
                float: left;
                font-size: 20px;
                color: #fff;
                margin: 0 20px 0 0;
                transition: all 0.3s ease-in-out 0s;
            }

            .serviceBox .title {
                display: inline-block;
                font-size: 20px;
                color: #041829;
                border-bottom: 3px solid #d9e7ed;
                padding-bottom: 6px;
                margin: 0 0 20px 0;
                transition: all 0.3s ease-in-out 0s;
            }

            .serviceBox:hover .title {
                border-color: #27c9c6;
                color: #fff;
            }

            .serviceBox .description {
                font-size: 16px;
                color: #929a9c;
                margin: 0 0 11px 0;
            }

            .serviceBox .read-more {
                display: inline-block;
                font-size: 16px;
                font-weight: 500;
                color: #27c9c6;
                text-transform: capitalize;
            }

                .serviceBox .read-more:hover {
                    letter-spacing: 0.3px;
                    color: #27c9c6;
                }

                .serviceBox .read-more:after {
                    content: "\f0da";
                    font-family: 'FontAwesome';
                    font-size: 16px;
                    color: #27c9c6;
                    margin-left: 7px;
                    transition: all 0.2s ease 0s;
                }

        .dHeader {
            background-color: #0B3C5D;
            color: #fff;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #0F1626;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 16px;
                color: white;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover, .offcanvas a:focus {
                    color: #f1f1f1;
                }

            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        .headerDell {
            background-color: #1D2731;
            color: white;
            text-transform: uppercase;
            margin-bottom: 30px;
        }

        .affix {
            top: 0;
            width: 100%;
        }

            .affix + .tab-content {
                padding-top: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding: 0px;
        }

        .open .dropdown-toggle {
            color: #fff;
            background-color: #555 !important;
        }

        .dropdown-menu li a {
            color: #000 !important;
        }

            .dropdown-menu li a:hover {
                background-color: red !important;
            }
    </style>
</head>

<body id="main">
    <!-- Header -->
    <div class="dHeader">
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <ul class="sidebar-menu" id="sideMenu">
                <li class="sidebar-header">HOME</li>
                <li>
                    <a href='@Url.Action("Index", "Home",new { id = "" })'>
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-header">REPORTS</li>
            </ul>
        </div>
        <span style="font-size:30px;cursor:pointer" onclick="openNav()" id="bar">&#9776;</span>
        <header class="w3-container w3-center w3-padding-1">
            <h1><b>DELL PLATINUM SERVICES</b></h1>
            <p>Welcome to the Services of <span class="w3-tag">DELL.</span></p>
        </header>
    </div>
    <div class="headerDell">
        <ul class="nav nav-tabs">
            <li><a data-toggle="tab tooltip" title="Home Page" href='@Url.Action("Index", "Home",new { id = "" })'>Home</a></li>
            <li class="active"><a data-toggle="tab tooltip" title="View Reports" href='@Url.Action("GetDeviceHistory", "Report",new { reportName = "Device History" })'>Reports</a></li>
        </ul>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="text-center">        
        <p>DPS&reg;Dell Platinum Services &copy;@DateTime.Now.Year</p>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>